### ISSUE TITLE
No output after 'Init CC1100...' (Arduino)

### ISSUE THREAD

**Issue by DrahcPro** [SpaceTeddy/CC1101#56]
I have installed the package and library, followed the instructions to install the script onto an arduino but it only prints "Init CC1100..." and nothing else. I've already jumped into the code at it must be going wrong somewhere between line 374 and 405 because after that there should be an output. Any tips on how to debug this further?

I am using an arduino mega 2560 together with an E07-M1101D-SMA chip.

**Comment by SpaceTeddy** [comment]
Hi @DrahcPro ,
Does it mean you fixed your problem and it is working now? 
may you tell us the issue?

thx

**Comment by DrahcPro** [comment]
The specific issue is not the case anymore (probs user error), I still have other issues which I am trying to figure out though. Namely tx side example is working but rx side is not receiving.

I'll be trying some stuff out today and tomorrow and will post a new issue if I can't figure it out.

**Comment by SpaceTeddy** [comment]
well, unfortunatly I have no hardware for this project anymore and I can not give good support, but as I remenber right I used a M16 AVR. In the beginning I had some trouble with the Interrupt routine  and I would suggest that you check the GPIO2 of the RF board board if ther is a HIGH level signal after sending the package with the TX Demo. If the state changes from LOW to HIGH, than you should check the Pinning again and check if the Interrupt triggers on the right GPIO of the Arduino board.
You can also try to implement GPIO2 polling instead of Interrupt. This is more easy for the beginning.

**Comment by DrahcPro** [comment]
Alright, I'll check that first 👍

**Comment by DrahcPro** [comment]
Ow and now I have your attention, could you maybe add a note in the readme that the pinout for arduino MEGA is not the same as UNO this caused a fair bit of confusion for me as well (SPI are on the UNO in the 10s and in the MEGA on the 50s)
